### ISSUE TITLE
Running algorithms in large maps

### ISSUE THREAD

**Issue by chenweigu** [hikashi/multi-robot-rrt-exploration-noetic#5]
It works well in small size maps. but can you tell me what parameters I need to change if I want to run it in a large map (20m*20m)?

**Comment by hikashi** [comment]
There is no definitive answer to this.
For starters, it depends on the configuration of the robot.
Let's say you are using the same robot as this version, you may consider tuning the ETA or GETA, info radius to a suitable length (i.e. ETA and GETA to 1.5 and radius info to 1.5) as well. 
Also, try to fix the map size as the map merging module tends to be unstable when there is expansion. Other than that, most issues will come from the localization due to drift, for example, the frontier point will be allocated to obstacles instead of free space. This might cause problems.
I hope this will help you explore a larger map using this algorithm.

Regards,
Billy Lau
